const minjiObject = {
  login: 'mandy0529',
  id: 59499779,
  node_id: 'MDQ6VXNlcjU5NDk5Nzc5',
  avatar_url: 'https://avatars.githubusercontent.com/u/59499779?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/mandy0529',
  html_url: 'https://github.com/mandy0529',
  followers_url: 'https://api.github.com/users/mandy0529/followers',
  following_url:
    'https://api.github.com/users/mandy0529/following{/other_user}',
  gists_url: 'https://api.github.com/users/mandy0529/gists{/gist_id}',
  starred_url: 'https://api.github.com/users/mandy0529/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/mandy0529/subscriptions',
  organizations_url: 'https://api.github.com/users/mandy0529/orgs',
  repos_url: 'https://api.github.com/users/mandy0529/repos',
  events_url: 'https://api.github.com/users/mandy0529/events{/privacy}',
  received_events_url: 'https://api.github.com/users/mandy0529/received_events',
  type: 'User',
  site_admin: false,
  name: 'Minji Kim ✨',
  company: null,
  blog: 'https://gooddayminji.site/',
  location: 'Seoul',
  email: null,
  hireable: null,
  bio: 'Good day, Minji 🌳',
  twitter_username: null,
  public_repos: 106,
  public_gists: 0,
  followers: 1,
  following: 1,
  created_at: '2020-01-04T08:21:07Z',
  updated_at: '2021-12-22T16:04:22Z',
};

export {minjiObject};
